In [ ]:
import torch.nn as nn

batch_size = 1
one_hot_size = 1
sequence_width = 5
data = torch.ones(batch_size, one_hot_size, sequence_width)
conv1 = nn.Conv1d(in_channels=one_hot_size, out_channels=1,
               kernel_size=3)
intermediate1 = conv1(data)
print(data.size())
print(intermediate1.size())
print("DATA=", data)
print("INTERMEDIATE1=", intermediate1)
print("CONV1 weights=", conv1.weight.data.numpy())
print("CONV1 bias=", conv1.bias)


torch.Size([1, 1, 5])
torch.Size([1, 1, 3])
DATA= tensor([[[1., 1., 1., 1., 1.]]])
INTERMEDIATE1= tensor([[[1.4151, 1.4151, 1.4151]]], grad_fn=<SqueezeBackward1>)
CONV1 weights= [[[0.40477586 0.49083853 0.28156137]]]
CONV1 bias= Parameter containing:
tensor([0.2379], requires_grad=True)


In [ ]:
conv2 = nn.Conv1d(in_channels=one_hot_size, out_channels=1,
               kernel_size=2)
final = conv2(intermediate1)

print(final.size())
print("FINAL=", final)
print("CONV2 weights=", conv2.weight.data.numpy())
print("CONV2 bias=", conv2.bias)




torch.Size([1, 1, 2])
FINAL= tensor([[[0.7029, 0.7029]]], grad_fn=<SqueezeBackward1>)
CONV2 weights= [[[0.10144985 0.68418235]]]
CONV2 bias= Parameter containing:
tensor([-0.4088], requires_grad=True)


In [ ]:
print(torch.mean(final, dim=2))
print(torch.max(final, dim=2))
print(torch.sum(final, dim=2))

tensor([[0.7029]], grad_fn=<MeanBackward1>)
torch.return_types.max(
values=tensor([[0.7029]], grad_fn=<MaxBackward0>),
indices=tensor([[1]]))
tensor([[1.4058]], grad_fn=<SumBackward1>)
