Looking up the properties of a tensor:

In [ ]:
import torch

In [ ]:
def describe(x):
  print("Type: {}".format(x.type()))
  print("Shape/size: {}".format(x.shape))
  print("Values: \n{}".format(x))

In [ ]:
describe(torch.Tensor(2,3))

Type: torch.FloatTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[1.8807e-35, 0.0000e+00, 3.7835e-44],
        [0.0000e+00,        nan, 0.0000e+00]])


Alternative ways for defining a tensor:

In [ ]:
describe(torch.zeros(2,3))

Type: torch.FloatTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [ ]:
describe(torch.ones(2,3))

Type: torch.FloatTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [ ]:
X=torch.ones(2,3)
describe(X.fill_(5))

Type: torch.FloatTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[5., 5., 5.],
        [5., 5., 5.]])


In [ ]:
describe(torch.tensor([[1,2,3],[4,5,6]]))

Type: torch.LongTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[1, 2, 3],
        [4, 5, 6]])


In [ ]:
describe(torch.rand(2,3)) # uniform distribution

Type: torch.FloatTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[0.1519, 0.0343, 0.0260],
        [0.5097, 0.0805, 0.9201]])


In [ ]:
describe(torch.randn(2,3)) # normal distribution

Type: torch.FloatTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[-0.9631,  0.0646, -1.9911],
        [-1.2106, -0.9436,  1.0816]])


Arithmetic operations for tensors

In [ ]:
a=torch.tensor([4, 3])
b=torch.tensor([2, 6])
print(a+b)
print(a-b)
print(a*b)
print(a // b)
print(a**b)

tensor([6, 9])
tensor([ 2, -3])
tensor([ 8, 18])
tensor([2, 0])
tensor([ 16, 729])


Reduction sum and mean

In [ ]:
a = torch.ones(3,4)
describe(a.sum())

Type: torch.FloatTensor
Shape/size: torch.Size([])
Values: 
12.0


In [ ]:
describe(a.mean())

Type: torch.FloatTensor
Shape/size: torch.Size([])
Values: 
1.0


Non-reduction sum: sometimes it can be useful to keep the number of axes unchanged when invoking the function for calculating sum and mean.

In [ ]:
describe(a.sum(axis=1, keepdim=True))

Type: torch.FloatTensor
Shape/size: torch.Size([3, 1])
Values: 
tensor([[4.],
        [4.],
        [4.]])


In [ ]:
describe(a.sum(axis=0, keepdim=True))

Type: torch.FloatTensor
Shape/size: torch.Size([1, 4])
Values: 
tensor([[3., 3., 3., 3.]])


In [ ]:
describe(a.mean(axis=0, keepdim=True))

Type: torch.FloatTensor
Shape/size: torch.Size([1, 4])
Values: 
tensor([[1., 1., 1., 1.]])


Dot Product

In [ ]:
a=torch.ones(3)
print(a)
b=torch.Tensor([2,3,4])
print(b)
print(torch.dot(b,a))

tensor([1., 1., 1.])
tensor([2., 3., 4.])
tensor(9.)


Matrix Multiplication

In [ ]:
import numpy as np
a=torch.Tensor([[1,2,3]])
b=torch.ones(3,1)
print("a:")
describe(a)
print("b:")
describe(b)
print("a.b:", torch.mm(a,b))
print("b.a:", torch.mm(b,a))

a:
Type: torch.FloatTensor
Shape/size: torch.Size([1, 3])
Values: 
tensor([[1., 2., 3.]])
b:
Type: torch.FloatTensor
Shape/size: torch.Size([3, 1])
Values: 
tensor([[1.],
        [1.],
        [1.]])
a.b: tensor([[6.]])
b.a: tensor([[1., 2., 3.],
        [1., 2., 3.],
        [1., 2., 3.]])


Norms

In [ ]:
a=torch.Tensor([-3,4])
describe(a)
print(np.linalg.norm(a))

Type: torch.FloatTensor
Shape/size: torch.Size([2])
Values: 
tensor([-3.,  4.])
5.0
